// Package gendocs generates the binder command reference from binder's own
// live Cobra command tree. It is the single source of the generation logic,
// shared by the cmd/gendocs generator program and the drift test in this
// package, so the committed docs/commands/ projection cannot disagree with
// the fixture the drift gate checks against.
//
// Output is deterministic: the auto-generated timestamp tag Cobra normally
// appends is disabled, Cobra sorts subcommands, and no host-specific paths or
// timestamps are written. Regeneration is therefore idempotent.
package gendocs

import (
	"os"
	"sort"
	"strings"

	"github.com/ghchinoy/binder/cmd"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

// Root returns the binder root command with the auto-generated timestamp tag
// disabled on every command in the tree, so generated markdown is stable.
func Root() *cobra.Command {
	root := cmd.NewRootCmd()
	disableAutoGenTag(root)
	return root
}

// disableAutoGenTag walks the command tree and turns off Cobra's
// "Auto generated by spf13/cobra on <date>" footer, the only non-deterministic
// element cobra/doc would otherwise emit.
func disableAutoGenTag(c *cobra.Command) {
	c.DisableAutoGenTag = true
	for _, child := range c.Commands() {
		disableAutoGenTag(child)
	}
}

// Generate writes the command reference into dir, one markdown file per
// command, plus a stable README.md index. dir is created if it does not exist.
// The output is deterministic and safe to diff byte-for-byte.
func Generate(dir string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	root := Root()

	// Keep links repo-relative and identity-mapped so no host path leaks.
	linkHandler := func(name string) string { return name }
	// No frontmatter or preamble: the site copies these verbatim and adds its
	// own presentation layer. An empty prepender keeps files portable.
	filePrepender := func(string) string { return "" }

	if err := doc.GenMarkdownTreeCustom(root, dir, filePrepender, linkHandler); err != nil {
		return err
	}
	return writeIndex(dir, root)
}

// writeIndex emits a deterministic README.md linking every command page in a
// stable, sorted order.
func writeIndex(dir string, root *cobra.Command) error {
	var lines []string
	collect(root, &lines)
	sort.Strings(lines)

	var b strings.Builder
	b.WriteString("# binder command reference\n\n")
	b.WriteString("Generated from binder's Cobra command tree by `make docs` ")
	b.WriteString("(`cmd/gendocs`). Do not edit by hand; a drift test ")
	b.WriteString("(`internal/gendocs`) fails CI if these files fall out of sync ")
	b.WriteString("with the command tree.\n\n")
	for _, line := range lines {
		b.WriteString(line)
		b.WriteString("\n")
	}
	return os.WriteFile(dir+"/README.md", []byte(b.String()), 0o644)
}

// collect appends a sorted-friendly markdown list entry for cmd and recurses
// into its subcommands. Only commands that produce a doc file (available,
// non-help commands) are listed, mirroring cobra/doc's own selection.
func collect(c *cobra.Command, lines *[]string) {
	if c.IsAvailableCommand() || c == c.Root() {
		file := strings.ReplaceAll(c.CommandPath(), " ", "_") + ".md"
		*lines = append(*lines, "- ["+c.CommandPath()+"]("+file+") — "+c.Short)
	}
	for _, child := range c.Commands() {
		if !child.IsAvailableCommand() || child.IsAdditionalHelpTopicCommand() {
			continue
		}
		collect(child, lines)
	}
}
