// Package version is the single source of the producer actor EXEMPLAR that
// binder shows in user-facing help and error text ("e.g. binder/0.5.3").
//
// It exists because of an import-direction problem (issue #60). The live
// version lives in `var binder.Version` (pkg/binder), because that is what
// goreleaser's
// -ldflags "-X github.com/ghchinoy/binder/pkg/binder.Version=<tag>" can
// reach. But the exemplar is needed by internal/config (the shared actor-forms
// hint, used by both the flag validator and the config-load validator) and by
// pkg/mcp — and `cmd` imports both, so neither can import `cmd` back. A leaf
// package that `cmd` PUSHES the resolved version into is the only direction that
// works. (`cmd`'s init resolves and normalizes binder.Version, then pushes it
// here; see cmd/root.go.)
//
// # Initialization order (the trap this package is built around)
//
// The failure mode #60 warns about is an exemplar that renders EMPTY because it
// was read before the version was resolved. Two things make that unreachable
// here:
//
//  1. `current` defaults to the unresolved sentinel, and Set() rejects values
//     that are not resolved versions, so the rendered exemplar is never "binder/".
//  2. Every consumer reads the exemplar at RUN time (flag registration happens
//     inside NewRootCmd/NewConvertCmd/NewEnrichCmd, which main() calls; the
//     invalid-actor errors are raised per invocation). Nothing reads it from a
//     package-level var initializer, so cmd's init() — which resolves Version
//     through normalizeVersion and then calls Set — always runs first. Go
//     guarantees all package init() functions complete before main() begins.
//
// Point 2 is an invariant, not an accident: do NOT consume ActorExemplar() from
// a package-level variable initializer. A var initializer in a package that
// `cmd` imports runs BEFORE cmd's init(), and would capture the unresolved form.
package version

// Producer is binder's producer name in the `<producer>/<version>` actor form
// (OKF spec §7). The canonical rendering has no leading "v" on the version —
// see cmd/root.go's normalizeVersion, the single funnel every version source
// passes through.
const Producer = "binder"

// unresolvedExemplar is what the exemplar renders as when no release version is
// known: the abstract placeholder, not a fabricated number and not the empty
// string.
//
// Why a placeholder rather than "binder/dev": the docs/commands/ reference is
// generated by `go run ./cmd/gendocs` (an UNSTAMPED build) and is pinned
// byte-for-byte by the internal/gendocs drift test (also unstamped). Rendering
// the live value there would publish "binder/dev" in the committed CLI
// reference — honest for the binary that produced it, wrong for the release the
// docs describe. The placeholder is true under every build, so the committed
// projection stays deterministic and can never go stale, while a real release
// binary (stamped by goreleaser, or `go install ...@vX.Y.Z` via
// debug.ReadBuildInfo) shows the concrete live version.
//
// It is also a VALID actor per okf.IsValidActor (one slash, non-empty sides, no
// whitespace), so a user who copies it verbatim gets a usable — if unhelpful —
// value rather than a usage error. Locked by TestExemplarIsAlwaysAValidActor.
const unresolvedExemplar = Producer + "/<version>"

// current is the resolved release version in canonical (no leading "v") form,
// or "" when none is known. Set by cmd's init(); see the package doc for why
// the push direction is required and why no reader can observe the pre-Set
// value.
var current string

// Set publishes the resolved binder version. cmd's init() calls it with the
// value that has already passed through normalizeVersion, so this package never
// re-derives or re-normalizes — there is exactly one funnel and it stays in
// cmd/root.go.
//
// Values that are not a resolved release version are IGNORED rather than
// stored: "dev" (the unstamped default), "(devel)" (the build-info sentinel),
// "" and anything else that does not begin with a digit. That check is the
// reason an empty or sentinel version can never leak into user-facing text —
// the exemplar degrades to the placeholder instead. A resolved version always
// begins with a digit once normalizeVersion has stripped the leading "v"
// (0.5.3, 1.2.3-rc1, …).
func Set(v string) {
	if v == "" || v[0] < '0' || v[0] > '9' {
		return
	}
	current = v
}

// Current returns the resolved release version in canonical form, or "" when no
// release version is known (an unstamped `go build`/`go test` binary).
func Current() string { return current }

// PinUnresolved forces ActorExemplar back to the version-neutral placeholder.
//
// Its ONE intended caller is internal/gendocs.Root, which needs the generated
// docs/commands/ reference to be a pure function of the command tree. Without
// this, the reference would depend on how the generator itself was built:
// `go run ./cmd/gendocs` and `go test ./internal/gendocs` both report "(devel)"
// today, but `go build`-ing the generator inside a git checkout picks up a VCS
// pseudo-version, which would bake a machine-specific string into the committed
// docs and red the byte-equality drift test for the next person. Pinning makes
// the projection deterministic by construction rather than by coincidence.
//
// It is not a general-purpose reset: nothing else should unresolve the version.
func PinUnresolved() { current = "" }

// ActorExemplar returns the worked `<producer>/<version>` example for
// user-facing help and error text: "binder/0.5.3" on a release build,
// "binder/<version>" when no release version is known.
//
// This replaces the four hand-maintained "binder/0.3.0" literals #60 was filed
// against. It never returns "binder/" — see Set.
func ActorExemplar() string {
	if current == "" {
		return unresolvedExemplar
	}
	return Producer + "/" + current
}
