// Command gogolden derives the cross-language conformance golden (issue #171)
// from binder's Go source of truth.
//
// It reads the shared INPUT corpus (scripts/conformance/corpus.json) and, for
// each case, runs the REAL Go implementation and records what it actually
// produces:
//
//   - frontmatter cases run through native.Codec.ParseConcept, so the recorded
//     error text is the exact string fmt.Errorf emits in
//     internal/okf/native/native.go — not a copy of it;
//   - actor cases run through okf.IsHumanActor / okf.IsValidActor, so the
//     recorded booleans are whatever the real predicates in
//     internal/okf/trust.go return.
//
// The output JSON is the golden the other implementations (astro-okf TS, the
// validate-plugin.sh Python copy, the two testdata prose fixtures) are diffed
// against. Because it is generated by executing the real code, editing a Go
// error string or actor rule changes this golden automatically, which is what
// makes the conformance suite fail once per copy that did not follow. If this
// program ever hard-coded the strings, it would be a fourth copy rather than a
// derivation — so it must only ever OBSERVE the Go functions, never restate
// their literals.
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/ghchinoy/binder/internal/okf"
	"github.com/ghchinoy/binder/internal/okf/native"
)

type corpus struct {
	Frontmatter []struct {
		Name  string `json:"name"`
		Input string `json:"input"`
	} `json:"frontmatter"`
	Actors []string `json:"actors"`
}

type golden struct {
	Frontmatter []frontmatterResult `json:"frontmatter"`
	Actors      []actorResult       `json:"actors"`
}

type frontmatterResult struct {
	Name  string `json:"name"`
	Error string `json:"error"`
}

type actorResult struct {
	Actor   string `json:"actor"`
	IsHuman bool   `json:"isHuman"`
	IsValid bool   `json:"isValid"`
}

func main() {
	path := os.Getenv("OKF_CONFORMANCE_CORPUS")
	if len(os.Args) > 1 {
		path = os.Args[1]
	}
	if path == "" {
		fmt.Fprintln(os.Stderr, "usage: gogolden <corpus.json>  (or set OKF_CONFORMANCE_CORPUS)")
		os.Exit(2)
	}

	raw, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gogolden: reading corpus: %v\n", err)
		os.Exit(2)
	}
	var c corpus
	if err := json.Unmarshal(raw, &c); err != nil {
		fmt.Fprintf(os.Stderr, "gogolden: parsing corpus: %v\n", err)
		os.Exit(2)
	}

	codec := native.New()
	var g golden

	for _, fc := range c.Frontmatter {
		// Observe what the real codec does; record its actual error text.
		msg := ""
		if _, err := codec.ParseConcept("conformance.md", []byte(fc.Input)); err != nil {
			msg = err.Error()
		}
		g.Frontmatter = append(g.Frontmatter, frontmatterResult{Name: fc.Name, Error: msg})
	}

	for _, a := range c.Actors {
		// Observe the real predicates; record what they actually return.
		g.Actors = append(g.Actors, actorResult{
			Actor:   a,
			IsHuman: okf.IsHumanActor(a),
			IsValid: okf.IsValidActor(a),
		})
	}

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	if err := enc.Encode(g); err != nil {
		fmt.Fprintf(os.Stderr, "gogolden: encoding golden: %v\n", err)
		os.Exit(2)
	}
}
