// Command gogolden derives the cross-language conformance golden (issue #171)
// from binder's Go source of truth.
//
// It reads the shared INPUT corpus (scripts/conformance/corpus.json) and, for
// each case, runs the REAL Go implementation and records what it actually
// produces:
//
//   - frontmatter cases run through native.Codec.ParseConcept, so the recorded
//     error text is the exact string fmt.Errorf emits in
//     internal/okf/native/native.go — not a copy of it;
//   - actor cases run through okf.IsHumanActor / okf.IsValidActor, so the
//     recorded booleans are whatever the real predicates in
//     internal/okf/trust.go return.
//
// The output JSON is the golden the other implementations (astro-okf TS, the
// validate-plugin.sh Python copy, the two testdata prose fixtures) are diffed
// against. Because it is generated by executing the real code, editing a Go
// error string or actor rule changes this golden automatically, which is what
// makes the conformance suite fail once per copy that did not follow. If this
// program ever hard-coded the strings, it would be a fourth copy rather than a
// derivation — so it must only ever OBSERVE the Go functions, never restate
// their literals.
//
// Scope / residual: this golden covers the two STRUCTURAL frontmatter error
// strings and the two actor predicates named in #171. The parser-dependent
// wrapped-YAML error path (native.go's `invalid frontmatter: %w`) and
// okf.TrustTier / okf.IsStale are only transitively covered — tracked in #175.
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/ghchinoy/binder/internal/okf"
	"github.com/ghchinoy/binder/internal/okf/native"
)

type corpus struct {
	Frontmatter []struct {
		Name  string `json:"name"`
		Input string `json:"input"`
	} `json:"frontmatter"`
	Actors []string `json:"actors"`
}

type golden struct {
	// Canonical is a Go-OBSERVED record of the two structural frontmatter error
	// strings, produced by running the real codec over two minimal inputs whose
	// ONLY job is to trigger each structural path. These are inputs, not error
	// literals: the strings below are whatever Go actually emits, never restated
	// here. The conformance suite uses them to assert LOCALLY that the shared
	// corpus still exercises BOTH structural error paths — so the guarantee that
	// each string is bound cannot silently become vacuous if the corpus changes
	// (issue #171 round 3). If a future Go change stops producing an error for
	// one of these inputs, the corresponding field goes empty and the coverage
	// check fails closed.
	Canonical   canonical           `json:"canonical"`
	Frontmatter []frontmatterResult `json:"frontmatter"`
	Actors      []actorResult       `json:"actors"`
}

type canonical struct {
	UnterminatedError string `json:"unterminatedError"`
	NonmappingError   string `json:"nonmappingError"`
}

type frontmatterResult struct {
	Name  string `json:"name"`
	Error string `json:"error"`
}

type actorResult struct {
	Actor   string `json:"actor"`
	IsHuman bool   `json:"isHuman"`
	IsValid bool   `json:"isValid"`
}

// observeErr runs the real codec over input and returns Go's actual error text
// (or "" if it did not error). It never restates a literal — the returned string
// is whatever native.go emitted.
func observeErr(codec *native.Codec, input string) string {
	if _, err := codec.ParseConcept("conformance.md", []byte(input)); err != nil {
		return err.Error()
	}
	return ""
}

func main() {
	path := os.Getenv("OKF_CONFORMANCE_CORPUS")
	if len(os.Args) > 1 {
		path = os.Args[1]
	}
	if path == "" {
		fmt.Fprintln(os.Stderr, "usage: gogolden <corpus.json>  (or set OKF_CONFORMANCE_CORPUS)")
		os.Exit(2)
	}

	raw, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gogolden: reading corpus: %v\n", err)
		os.Exit(2)
	}
	var c corpus
	if err := json.Unmarshal(raw, &c); err != nil {
		fmt.Fprintf(os.Stderr, "gogolden: parsing corpus: %v\n", err)
		os.Exit(2)
	}

	codec := native.New()
	var g golden

	// Observe the two structural errors Go produces from minimal triggering
	// inputs. These inputs live here (not in the corpus) so the canonical record
	// is independent of whatever the shared corpus happens to contain — that
	// independence is exactly what lets the coverage check assert the corpus
	// still reproduces both. observeErr records Go's actual err.Error(), so no
	// literal is restated.
	g.Canonical.UnterminatedError = observeErr(codec, "---\nname: unterminated fence, never closed\n")
	g.Canonical.NonmappingError = observeErr(codec, "---\n- top-level node is a sequence, not a mapping\n---\n")

	for _, fc := range c.Frontmatter {
		// Observe what the real codec does; record its actual error text.
		msg := ""
		if _, err := codec.ParseConcept("conformance.md", []byte(fc.Input)); err != nil {
			msg = err.Error()
		}
		g.Frontmatter = append(g.Frontmatter, frontmatterResult{Name: fc.Name, Error: msg})
	}

	for _, a := range c.Actors {
		// Observe the real predicates; record what they actually return.
		g.Actors = append(g.Actors, actorResult{
			Actor:   a,
			IsHuman: okf.IsHumanActor(a),
			IsValid: okf.IsValidActor(a),
		})
	}

	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	if err := enc.Encode(g); err != nil {
		fmt.Fprintf(os.Stderr, "gogolden: encoding golden: %v\n", err)
		os.Exit(2)
	}
}
